version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mqtt-prueba
    networks:
      - code-network
    ports:
      - 27018:27017
    volumes:
      - ./tmp/mongodb:/data/db

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - ${MQTT_PORT}:${MQTT_PORT}
      - 9001:9001
    networks:
      - code-network
    volumes:
      - ./supply/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./supply/users:/mosquitto/config/users
      - ./tmp/mosquitto/data:/mosquitto/data
      - ./tmp/mosquitto/log:/mosquitto/log
    restart: always

  mqtt-bridge:
    build: ./mqtt-bridge
    container_name: mqtt-bridge
    depends_on:
      - rest-api
    networks:
      - code-network
    restart: always
    user: "node"
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./mqtt-bridge:/app
      - /app/node_modules

  rest-api:
    build: ./rest-api
    container_name: rest-api
    depends_on:
      - mongo
    networks:
      - code-network
    restart: always
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 3001:3001 #to outside host:container
    volumes:
      - ./rest-api:/app
      - /app/node_modules

  angular-app:
    image: nginx
    container_name: angular-app
    networks:
      - code-network
    restart: always
    ports:
      - 80:80
    volumes:
      - ./angular-charts/dist/angular-charts:/usr/share/nginx/html
networks:
  code-network:
    driver: bridge
