FROM node:alpine

ENV NODE_OPTIONS=--max_old_space_size=1024

RUN mkdir /app && chown node:node /app

WORKDIR /app

COPY --chown=node:node package.json package-lock.json* ./
RUN npm install

COPY --chown=node:node . .

CMD ["npm", "start"]