var loc = location.toString().split(`/`);
var BASE_URL = `http://${loc[2]}`;
export const environment = {
  production: true,
  // OLD VARIABLES:
  // API_URL_PAISES_OLD: `http://${BASE_URL}:3001/api/paises/`,
  // API_URL_PROVINCIAS_OLD: `http://${BASE_URL}:3001/api/provincias/`,
  // API_URL_LOCALIDADES_OLD: `http://${BASE_URL}:3001/api/localidad/`,
  API_BASE_URL: BASE_URL,
  API_URL_USERS: `${BASE_URL}:3001/api/users/`,
  API_URL_ROLES: `${BASE_URL}:3001/api/role/`,
  API_URL_RGENERAL: `${BASE_URL}:3001/api/registro-general/`,
  API_URL_RGENERALTS: `${BASE_URL}:3001/api/registro-general-ts/`,
  API_URL_VARIABLES: `${BASE_URL}:3001/api/variables/`,
  API_URL_PAISES: `https://countriesnow.space/api/v0.1/countries/`,
  API_URL_PROVINCIAS: `https://countriesnow.space/api/v0.1/countries/states`,
  API_URL_LOCALIDADES: `https://countriesnow.space/api/v0.1/countries/state/cities`,
  API_URL_EMPRESAS: `${BASE_URL}:3001/api/empresas/`,
  API_URL_PLANTA: `${BASE_URL}:3001/api/empresa-planta/`,
  API_URL_TIPO_MAQUINA: `${BASE_URL}:3001/api/tipo-maquina/`,
  API_URL_MAQUINA: `${BASE_URL}:3001/api/maquinas/`,
  API_URL_LINEA_PRODUCCION: `${BASE_URL}:3001/api/linea-produccion/`,
  API_URL_PROCESO: `${BASE_URL}:3001/api/proceso/`,
  API_URL_TRIGGER: `${BASE_URL}:3001/api/trigger/`,
  API_URL_RTOKEN: `${BASE_URL}:3001/api/refresh`,
  API_URL_ARGENTINA_PROVINCIAS: `https://apis.datos.gob.ar/georef/api/provincias?orden=nombre&campos=basico&max=30`,
  API_URL_ARGENTINA_DEPARTAMENTOS: `https://apis.datos.gob.ar/georef/api/departamentos?provincia=`,
  API_URL_ARGENTINA_LOCALIDADES: `https://apis.datos.gob.ar/georef/api/localidades?provincia=`,
  API_URL_CHARTS: `${BASE_URL}:3001/api/charts/`,
};
