export const environment = {
  production: false,
  API_URL_USERS: 'http://localhost:3001/api/users',
  API_URL_ROLES: 'http://localhost:3001/api/role',
  API_URL_RGENERAL: 'http://localhost:3001/api/registro-general/',
  API_URL_VARIABLES: 'http://localhost:3001/api/variables',
  API_URL_PAISES: 'http://localhost:3001/api/paises',
  API_URL_PROVINCIAS: 'http://localhost:3001/api/provincias',
  API_URL_LOCALIDADES: 'http://localhost:3001/api/localidad',
  API_URL_EMPRESAS: 'http://localhost:3001/api/empresas',
  API_URL_PLANTA: 'http://localhost:3001/api/empresa-planta',
  API_URL_TIPO_MAQUINA: 'http://localhost:3001/api/tipo-maquina',
  API_URL_MAQUINA: 'http://localhost:3001/api/maquinas',
  API_URL_LINEA_PRODUCCION: 'http://localhost:3001/api/linea-produccion',
  API_URL_PROCESO: 'http://localhost:3001/api/proceso',
  API_URL_TRIGGER: 'http://localhost:3001/api/trigger',
};
