FROM node:lts

# Change directory so that our commands run inside this new directory
WORKDIR /home/node/app

# Copy dependency definitions
COPY package*.json /home/node/app/

# Install dependecies
RUN npm install

# Get all the code needed to run the app
COPY . .

# Expose the port the app runs in
EXPOSE 4200

# Serve the app
